### PR TITLE
Issue26

### PR DESCRIPTION
**Pull request by pauliyobo**
Probably merging it now wouldn't be advisable  yet unless we have a copy of the old version and unless we can keep the branch separated from master.

### CODE REVIEW

**Comment by NicklasTegner** [comment]
Hi
With The following changes to line 37  (in PodSixNet/test.py) allows the rest of the test cases succeed.

self.assertEqual(self.endpoint_bad.isConnected, False)


Good work on the pr and hope it get merged to master soon.

**Comment by chr15m** [comment]
@NicklasTegner if you add your change so that the tests pass I can merge.

**Comment by NicklasTegner** [comment]
@chr15m  I have tried but as I'm not the author of this pr i cannot add the changes (I think).

**Comment by pauliyobo** [comment]
@NicklasTegner thanks for the catch. I added  your fix to the PR.

**Comment by NicklasTegner** [comment]
What is the status of this merge. I see that it passes but any timeframe for when it will be merged.

**Comment by chr15m** [comment]
It passes but it breaks backwards compatibility.

**Comment by nonoesimposible** [comment]
I am getting an error when trying to run the Chat example on Python 3.8.2. After running one instance of `ChatServer.py` and two instances of `ChatClient.py`, I attempt to send a message and get

```
Exception ignored in thread started by: <bound method Client.InputLoop of <__main__.Client object at 0x7f9303b9bd60>>
Traceback (most recent call last):
  File "ChatClient.py", line 33, in InputLoop
    connection.send({"action": "message", "message": stdin.readline().rstrip("\n".encode())})
TypeError: rstrip arg must be None or str
```

This doesn't happen under `chr15m/master` (as of `514418c`).

**Comment by nonoesimposible** [comment]
Additionally, running `test.py` yields:

```
connection
error: uncaptured python exception, closing channel <asynchat.async_chat localhost:31429 at 0x7f1802669b20> (<class 'ConnectionRefusedError'>:[Errno 111] Connection refused [/usr/lib/python3.8/asyncore.py|read|83] [/usr/lib/python3.8/asyncore.py|handle_read_event|417] [/usr/lib/python3.8/asyncore.py|handle_connect_event|425])
```

I wonder if something got changed between 3.7 and 3.8?

**Comment by pauliyobo** [comment]
alright then since @chr15m  suggested to make a pull request to the new branch created, I'm going to close this PR and open a new one which points to the new branch.

**Pull request closed without merging**
